### ISSUE TITLE
Unknown type .bytes in type RasterImage

### ISSUE THREAD

**Issue by jo-me** [woven-planet/go-zserio#107]
Hi,

we're seeing errrors regarding an apparently unsupported type **_RasterImage_**.

The error is
`Error: parse schema: resolve types: smart.types.bytes, field RasterImage: unknown type: .bytes (type not found in package)`

RasterImage is a type in the smart module:
```
/** Unwrapped image data. */
subtype bytes RasterImage;
```

As we currently do not need this specific type our workaround for now is commenting out this definition along with the 2 services
```
  RasterImage getImage(RasterTileImageRequest);
  RasterImage getImageVersioned(RasterTileImageVersionRequest);
```
which removes the error during code generation.

Jochen Mehlhorn <jochen.mehlhorn@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH

[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by Danaozhong** [comment]
Hi @jo-me , thank you for the problem report!

I had a look at the necessary work to support `zserio 2.11.0`, and we will need to implement support for the [bytes type](http://zserio.org/doc/ZserioLanguageOverview.html#language-guide) that was added in `zserio 2.9`.
Looking at the zserio specification, it seems to be very similar to the extern type, but storing bytes instead of bits.

Do you want to give it a try to add support for the bytes type? Alternatively, I can have a look next week.

**Comment by jo-me** [comment]
Thanks @Danaozhong , with the latest version on main branch errors regarding this type are gone
