### ISSUE TITLE
Import cycle in smart module 2023.08

### ISSUE THREAD

**Issue by jo-me** [woven-planet/go-zserio#125]
Hi,

when generating the `smart` package with schema version 2023.08 (using latest go-zserio), it creates an import cycle between

smart/metadata and smart/object packages because the field
	`ObjectClass `of type `smart_object.SmartLayerObjectClass`

was added to struct `SmartLayerRegistryMetadata` in the metadata package.

Any ideas how to resolve this?

Thanks!

Jochen Mehlhorn <jochen.mehlhorn@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH

[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by Danaozhong** [comment]
Hi @jo-me ,
Thank you for the problem report and my sincere apologies for the late reply!
In fact, we had the issue in the past (https://github.com/woven-planet/go-zserio/issues/102), and decided that the best fix is to resolve the cyclic import in the serialization instructions (which was fixed in the `display` module).
My recommendation would be to raise a ticket at https://developer.nds.live/, and request the module to be slightly changed to resolve the cyclic import.

From `go-zserio`, we currently don't have a plan to support cyclic imports.

**Comment by jo-me** [comment]
Thanks for the hint @Danaozhong ,  apparently this is a known issue and solved with the December schema release..
