### ISSUE TITLE
Errors after setting up dev environment

### ISSUE THREAD

**Issue by jo-me** [woven-planet/go-zserio#135]
I followed the CONTRIBUTING readme but vscode still shows some errors:

![image](https://github.com/woven-planet/go-zserio/assets/10351272/8c46b977-d70f-47ee-854f-9e21eb0e0ea3)

![image](https://github.com/woven-planet/go-zserio/assets/10351272/01649d6e-6611-41c5-a676-a0a04c7f5be9)

is something missing? 

Jochen Mehlhorn <jochen.mehlhorn@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH

[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by aignas** [comment]
I also think that we should update the instructions to either point to the official docs: https://github.com/bazelbuild/rules_go/wiki/Editor-setup#visual-studio-code or to be the same. I noticed that the only difference between the screenshot and the upstream is:
```
  "go.enableCodeLens": {
    "runtest": false
  },
```

What is more, once #136 is merged, then the `go_sdk` path might change. You may need to set it up like:
```
  "go.toolsEnvVars": {
    "GOPACKAGESDRIVER": "${workspaceFolder}/bazel-out/bazel_env-opt/bin/bazel_env/bin/gopackagesdriver.sh"
  },
```

I don't think we need to specified the `goroot` path anymore, because the `go` binary that the `bazel_env` is going to provide should be sufficient for the VSCode plugin to work its magic. I have no VSCode to test this hypothesis though.

**Comment by wichert** [comment]
After merging #136 things are still not working correctly. The GOROOT is not valid:

![image](https://github.com/woven-planet/go-zserio/assets/199657/c1fc9906-d9f8-48a5-896e-d08f4e9cdadb)

And indeed `bazel-go-zserio/external/go_sdk` does not exist. What should be creating that folder @aignas ?
